repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: debug-statements
    - id: end-of-file-fixer
      exclude: github_deploy_key_ioos_erddapy.enc
    - id: check-docstring-first
    - id: check-added-large-files
      exclude_types: [yaml]
    - id: requirements-txt-fixer
    - id: file-contents-sorter
      files: requirements-dev.txt

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
    - id: flake8
      exclude: docs/source/conf.py
      args: [--max-line-length=105]

- repo: https://github.com/pycqa/isort
  rev: 5.6.4
  hooks:
    - id: isort
      additional_dependencies: [toml]
      args: [--project=erddapy, --multi-line=3, --lines-after-imports=2, --lines-between-types=1, --trailing-comma, --force-grid-wrap=0, --use-parentheses, --line-width=88]

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
  - id: mypy
    exclude: docs/source/conf.py
    args: [--ignore-missing-imports]

- repo: https://github.com/keewis/blackdoc
  rev: v0.2
  hooks:
    - id: blackdoc

- repo: https://github.com/econchick/interrogate
  rev: 1.3.1
  hooks:
    - id: interrogate
      exclude: ^(docs|setup.py|tests)
      args: [--config=pyproject.toml]

- repo: https://github.com/codespell-project/codespell
  rev: v1.17.1
  hooks:
    - id: codespell
      exclude: >
          (?x)^(
              .*\.yaml
          )$
      args:
        - --quiet-level=2

- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.3
  hooks:
    - id: pyupgrade
      args:
        - --py36-plus

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.0.1
  hooks:
    - id: add-trailing-comma
