language: minimal

env:
  global:
    # Doctr deploy key for ioos/erddapy
    - secure: "K7/ZsuH+mp28YhBgnHARRmneKyMqODpMcrzTBd4tK0rqtzRJYP7fel9JGhD/3mIqyp/E2qCF3Rk/YbonHvmsyjh0yBmyI1BtHIKEcsUgwYCMvkjWYTR0k5LYWqtyEl1pW5RSs5PAAKCcXDdxDoXkmLdJViDiKv6Mv8bnfppYJzPH7Z2xjfr9YxvhMiIngfLxtjPAm1GZKO75Ldhw1uE9eMqdxYHrENvTkbXTfS2o5ERCJppd8o8zeEsnUjE7fDXsvBTYP5Cdng9tYMVCFiIubQXLuYUGKjwVObR7AIczwx5so4yTly0k2gNrXtTpTW+hm6D8VQCGfJAXgfq3zpzKtUwBKpXVAP8K+NWy91eXOyr/rgcmFXjlzsN25/gPonyac92a7OQXRs5nsXKBY1KfUR2LyQapVZ89RpoA6w98X7OWeqvUg7uDuCdYAcsM3zVJMqIHvlr9UpqMvuluRMvX4iq9P/fD5Bq1WT3uJ3olLEXpbcaOeeaBpb3vO8IwiOEaNXR7A9iug3cpz4bP5nd5DET8Ki+lew6bkfiC5SaP+emS9WXD4uoKbiwrL6wz1kAdjOH6Exn4R0q8paJuaORiIfDEXAay39ZwBl3qzvt6Y7O3Y8i9oXG59+UKojSXxkPdF4byWA1nUF6wl4bpC4f/oJMoDtXiUdNv6WM8Jcndwdk="

matrix:
  fast_finish: true
  include:
    - name: "python-3.7"
      env: PY=3.7
    - name: "python-3.8"
      env: PY=3.8
    - name: "tarball"
      env: PY=3
    - name: "docs"
      env: PY=3

before_install:
  # Install micromamba and create TEST env.
  - |
    wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1
    ./micromamba shell init -s bash -p ~/micromamba
    export MAMBA_ROOT_PREFIX=~/micromamba
    export MAMBA_EXE=$(pwd)/micromamba
    . ${MAMBA_ROOT_PREFIX}/etc/profile.d/mamba.sh

    echo "micromamba version $(micromamba --version)"
    micromamba create --yes --name TEST python=$PY pip --file requirements.txt --file requirements-dev.txt --channel conda-forge
    micromamba activate TEST

install:
  - pip install -e . --no-deps --force-reinstall

script:
  - |
    if [[ $TRAVIS_JOB_NAME == python-* ]]; then
      cp -r tests/ /tmp
      pushd /tmp
      pytest -n 2 -rxs --cov=erddapy --vcr-record=none tests
      popd
    fi

  - |
    if [[ $TRAVIS_JOB_NAME == 'tarball' ]]; then
      python setup.py --version
      python setup.py sdist
      pip wheel . -w dist --no-deps
      check-manifest --verbose
      twine check dist/*
    fi

  - |
    if [[ $TRAVIS_JOB_NAME == 'docs' ]]; then
      set -e
      travis_wait jupyter nbconvert --to notebook --execute notebooks/00-quick_intro.ipynb --output=00-quick_intro-output.ipynb
      travis_wait jupyter nbconvert --to notebook --execute notebooks/01-longer_intro.ipynb --output=01-longer_intro-output.ipynb
      travis_wait jupyter nbconvert --to notebook --execute notebooks/02-extras.ipynb --output=02-extras-output.ipynb
      travis_wait jupyter nbconvert --to notebook --execute notebooks/03-searchfor.ipynb --output=03-searchfor-output.ipynb
      mv notebooks/*output.ipynb docs/source/
      pushd docs
      make clean html linkcheck
      popd

      if [ ! -z "$TRAVIS_TAG" ]; then DEPLOY_DIR="$TRAVIS_TAG"; else DEPLOY_DIR="$TRAVIS_BRANCH"; fi
      doctr deploy --command=doctr-versions-menu --no-require-master --build-tags "$DEPLOY_DIR"
    fi
