name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Setup Micromamba
      uses: mamba-org/provision-with-micromamba@v14
      with:
        environment-file: false

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: >
        micromamba create --name TEST python=${{ matrix.python-version }} pytest --file requirements.txt --channel conda-forge
        && micromamba activate TEST
        && python -m pip install -e . --no-deps --force-reinstall

    - name: Core Tests
      shell: bash -l {0}
      run: |
        micromamba activate TEST
        python -m pytest -rxs tests/test_erddapy.py

    - name: Full Tests
      shell: bash -l {0}
      run: |
        micromamba activate TEST
        micromamba install --file requirements-dev.txt
        python -m pytest -rxs --cov=erddapy --vcr-record=none tests